const Sdata=[
    { 
        id:"1",
        imgsrc:"https://avatars.dicebear.com/v2/avataaars/Bret.svg?options[mood][]=happy",
        name:"Leanne Graham",
        email:"Sincere@april.biz",
        phone:"1-770-736-8031 x56442",
        web:"http://hildegard.org",
    },
    {
        id:"2",
        imgsrc:"https://avatars.dicebear.com/v2/avataaars/Bret.svg?options[mood][]=happy",
        name:"Ervin Howell",
        email:"Shanna@melissa.tv",
        phone:"010-692-6593 x09125",
        web:"http://anastasia.net",
    },
    {
        id:"3",
        imgsrc:"https://avatars.dicebear.com/v2/avataaars/Bret.svg?options[mood][]=happy",
        name:"Clementine Bauch",
        email:"Nathan@yesenia.net",
        phone:"1-463-123-4447",
        web:"http://ramiro.info",
    },
    {
        id:"4",
        imgsrc:"https://avatars.dicebear.com/v2/avataaars/Bret.svg?options[mood][]=happy",
        name:"Patricia Lebsack",
        email:"Julianne.OConner@kory.org",
        phone:"493-170-9623 x156",
        web:"http://kale.biz",
    },
    {
        id:"5",
        imgsrc:"https://avatars.dicebear.com/v2/avataaars/Bret.svg?options[mood][]=happy",
        name:"Chelsey Dietrich",
        email:"Lucio_Hettinger@annie.ca",
        phone:"(254)954-1289",
        web:"http://demarco.info",
    },
     {
        id:"6",
        imgsrc:"https://avatars.dicebear.com/v2/avataaars/Bret.svg?options[mood][]=happy",
        name:"Mrs. Dennis Schulist",
        email:"Karley_Dach@jasper.info",
        phone:"1-477-935-8478 x6430",
        web:"http://ola.org",
    },
     {
        id:"7",
        imgsrc:"https://avatars.dicebear.com/v2/avataaars/Bret.svg?options[mood][]=happy",
        name:"Kurtis Weissnat",
        email:"Telly.Hoeger@billy.biz",
        phone:"210.067.6132",
        web:"http://elvis.io",
    },
    {
        id:"8",
        imgsrc:"https://avatars.dicebear.com/v2/avataaars/Bret.svg?options[mood][]=happy",
        name:"Nicholas Runolfsdottir V",
        email:"Sherwood@rosamond.me",
        phone:"586.493.6943 x140",
        web:"http://jacynthe.com",
    },
    {
        id:"9",
        imgsrc:"https://avatars.dicebear.com/v2/avataaars/Bret.svg?options[mood][]=happy",
        name:"Glenna Reichert",
        email:"Chaim_McDermott@dana.io",
        phone:"(775)976-6794 x41206",
        web:"http://conrad.com",
    },
    {
        id:"10",
        imgsrc:"https://avatars.dicebear.com/v2/avataaars/Bret.svg?options[mood][]=happy",
        name:"Clementina DuBuque",
        email:"Rey.Padberg@karina.biz",
        phone:"024-648-3804",
        web:"http://ambrose.net",
    },
];

export default Sdata;